# Generated by Django 3.2.7 on 2021-12-05 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('des', models.CharField(blank=True, max_length=250)),
                ('price', models.FloatField()),
                ('duration', models.IntegerField(default=1)),
                ('image', models.ImageField(default='default.png', upload_to='static/images/cource_img')),
                ('rating', models.FloatField(max_length=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('detailed_discription', models.TextField(blank=True, default='No Discription', null=True)),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='static/preview_video')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='static/pdf')),
                ('category', models.CharField(choices=[(1, 'latest'), (2, 'popular'), (3, 'art'), (4, 'Knowledge'), (5, 'Programing'), (6, 'Basic skills'), (7, 'setup, productivity and quality'), (8, 'busness'), (9, 'gaming'), (10, 'Advanced skills and Knowledge'), (11, 'outher')], max_length=225)),
                ('bought', models.IntegerField(max_length=250)),
                ('impresions', models.IntegerField(max_length=250)),
                ('clicks', models.IntegerField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='cource_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Teacher'), ('2', 'Student🔥')], max_length=225)),
                ('image', models.ImageField(default='default.png', upload_to='static/images/cource_img')),
                ('des', models.CharField(blank=True, max_length=250)),
                ('detailed_discription', models.TextField(blank=True, default='No Discription', null=True)),
                ('experience', models.IntegerField(default='2')),
                ('rating', models.FloatField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=250)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cource')),
            ],
        ),
        migrations.CreateModel(
            name='my_cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cource')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cource_user')),
            ],
        ),
        migrations.AddField(
            model_name='cource',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cource_user'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cource')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cource_user')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cource')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cource_user')),
            ],
        ),
    ]
