# Generated by Django 3.2.7 on 2021-12-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211206_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='static/preview_video'),
        ),
    ]
