# Generated by Django 4.0.4 on 2022-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211206_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='category',
            field=models.CharField(blank=True, choices=[(1, 'latest'), (2, 'popular'), (3, 'art'), (4, 'Knowledge'), (5, 'Programing'), (6, 'Basic skills'), (7, 'setup, productivity and quality'), (8, 'busness'), (9, 'gaming'), (10, 'Advanced skills and Knowledge'), (11, 'outher')], max_length=225),
        ),
        migrations.AlterField(
            model_name='cource',
            name='image',
            field=models.ImageField(default='default.png', upload_to='cource_images'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='preview_video/'),
        ),
        migrations.AlterField(
            model_name='cource_user',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
    ]
